version: '3'
services:

  # PHP Service (Workspace)
  app-plataforma:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php-plataforma
    container_name: workspace-plataforma
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    # Ajustado para o caminho da sua nova pasta
    working_dir: /var/www/plataforma
    volumes:
      - ./:/var/www/plataforma
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - plataforma-network

  # Nginx Service (Acessível em localhost:8081)
  webserver-plataforma:
    image: nginx:alpine
    container_name: nginx-plataforma
    restart: unless-stopped
    tty: true
    ports:
      - "8081:80"
      # Porta 443 removida para evitar conflito com o SAX, use a 8081
    volumes:
      - ./:/var/www/plataforma
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - plataforma-network

  # MySQL Service (Acessível em localhost:3307)
  db-plataforma:
    image: mysql:latest
    container_name: mysql-plataforma
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: plataforma_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata-plataforma:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - plataforma-network

  # PhpMyAdmin Service (Acessível em localhost:8082)
  phpmyadmin-plataforma:
    image: phpmyadmin
    container_name: phpmyadmin-plataforma
    restart: unless-stopped
    ports:
      - "8082:80"  
    environment:
      PMA_HOST: db-plataforma
      MYSQL_ROOT_PASSWORD: root
    networks:
      - plataforma-network

# Docker Networks
networks:
  plataforma-network:
    driver: bridge

# Volumes
volumes:
  dbdata-plataforma:
    driver: local